### ISSUE TITLE
OSUKS Name Dump Bug

### ISSUE THREAD

**Issue by FMGstaff** [fraternity-management-group/gms#21]
**Report name**
Member reports --> Name Dump+First and Last Name

**Client Id**
OSUKS

**Filter**
Active, Undergrads

**Expected behavior**
Should get a name dump with class years. 

**Additional context**
This is what the report is coming back with:

[OSUKS Bug Report_Thomas.pdf](https://github.com/fraternity-management-group/gms/files/5859345/OSUKS.Bug.Report_Thomas.pdf)

**Comment by jdfergason** [comment]
This is not an error with the system. The software has 12 unique entries for Thomas Sueiro. Only one of them has a last name, which is why for all the rest only Thomas shows up.

+--------+----------------+------------+-----------+
| id     | full_name      | first_name | last_name |
+--------+----------------+------------+-----------+
| 172180 | Thomas Sueiro  | Thomas     | Sueiro    |
| 172186 | Thomas Sueiro  | Thomas     |           |
| 172187 | Thomas Sueiro  | Thomas     |           |
| 172188 | Thomas Sueiro  | Thomas     |           |
| 172189 | Thomas Sueiro  | Thomas     |           |
| 172191 | Thomas Sueiro  | Thomas     |           |
| 172192 | Thomas Sueiro  | Thomas     |           |
| 172193 | Thomas Sueiro  | Thomas     |           |
| 172194 | Thomas Sueiro  | Thomas     |           |
| 172195 | Thomas Sueiro  | Thomas     |           |
| 172196 | Thomas Sueiro  | Thomas     |           |
| 172197 | Thomas Sueiro  | Thomas     |           |
