### ISSUE TITLE
PURKS Survey linking survey information to incorrect member

### ISSUE THREAD

**Issue by FMGstaff** [fraternity-management-group/gms#22]
**Form name**
PURKS Alumni Information Update INT [#70]

It looks like the automatic system entered this survey from James Campbell into John Prentice's profile. 

**Entry id**
#70 - James Campbell 

**Expected behavior**
Contact info, group codes etc. gets entered correctly into James Campbell's profile. 

**Additional context**

The social media's area also did not enter the handles, they instead put in "Facebook"...not sure why this is occurring. 

![Issue with Wufoo](https://user-images.githubusercontent.com/74945938/105565321-7c705400-5ce3-11eb-8500-3dff51a28004.PNG)

**Comment by jdfergason** [comment]
The social media entries are showing up as Facebook, Instagram, etc. because the form had been linked incorrectly. The multiple choice question "Which social media do you use? Please check all that apply. LinkedIn is very important for career networking and Facebook is the most used by alumni." was linked to those fields. Those values don't have the actual facebook, etc. profiles in them, instead it's just the string Facebook, etc. which is why they should not be linked to the social media values.

Since then the link has been updated to only use group codes for that question but nothing is linking to the social media fields.

**Comment by fmgmatt** [comment]
Jeremy, so if they say they are on a certain social media we add to the group code and if they add a link in the arts provided that goes to screen 1.

**Comment by jdfergason** [comment]
You will need to validate the user match is correct - this is the purpose of the confirm step. In this case it linked to John Prentice because the e-mail matched.
